import { Bookmark, MoreHorizontal } from 'lucide-react'
import { motion } from 'framer-motion'
import { memo } from 'react'
import { Badge, Button } from '../../../components/ui'
import { analyses, type Analysis } from '../data/placeholderData'

function riskTone(risk: number) { return risk > 70 ? 'text-danger bg-danger/10 border-danger/25' : risk > 40 ? 'text-warning bg-warning/10 border-warning/25' : 'text-success bg-success/10 border-success/25' }
export const RiskPill = memo(function RiskPill({ risk }: { risk: number }) { return <span className={`inline-flex min-w-11 justify-center rounded-full border px-2 py-1 text-xs font-semibold ${riskTone(risk)}`}>{risk}</span> })
export const AnalysisTable = memo(function AnalysisTable({ items = analyses }: { items?: Analysis[] }) { return <div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left"><thead className="border-b border-subtle font-mono text-[.61rem] uppercase tracking-[.14em] text-muted"><tr><th className="pb-3 font-medium">Analysis</th><th className="pb-3 font-medium">Type</th><th className="pb-3 font-medium">Risk</th><th className="pb-3 font-medium">Status</th><th className="pb-3 font-medium">Date</th><th /></tr></thead><tbody>{items.map((item, index) => <motion.tr initial={{ opacity: 0, y: 6 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .04 }} key={item.id} className="border-b border-subtle/70 last:border-0"><td className="py-4"><p className="text-sm font-medium">{item.title}</p><p className="font-mono text-[.62rem] text-muted">{item.id} · {item.category}</p></td><td className="py-4 text-xs text-muted">{item.type}</td><td className="py-4"><RiskPill risk={item.risk}/></td><td className="py-4"><Badge className={item.status === 'Review' ? 'border-warning/30 bg-warning/10 text-warning' : 'border-success/30 bg-success/10 text-success'}>{item.status}</Badge></td><td className="py-4 text-xs text-muted">{item.date}</td><td className="py-4 text-right"><Button aria-label={`Actions for ${item.title}`} variant="ghost" size="sm" className="px-2"><MoreHorizontal size={16}/></Button>{item.bookmarked && <Bookmark size={14} className="ml-1 inline text-violet" fill="currentColor"/>}</td></motion.tr>)}</tbody></table></div> })
