import { Activity, ArrowRight, ArrowUpRight, Bot, FileSearch, Image, Plus, Sparkles } from 'lucide-react'
import { MotionConfig, motion } from 'framer-motion'
import { Link } from 'react-router-dom'
import { Button } from '../../../components/ui'
import { useProfile } from '../../../providers/ProfileProvider'
import { DashboardHeroVisual } from './DashboardHeroVisual'

const status = ['Vision ready', 'RoBERTa ready', 'Emotion model', 'Agent network', 'Judge online', 'Meta judge online']
const features = ['Explainable AI', 'Emotion intelligence', 'Vision analysis', 'Research grade', 'Multi-agent reasoning', 'Live detection', 'Interactive reports', 'Browser extension', 'Enterprise security']

export function HeroBanner({ onContinue }: { onContinue?: () => void }) {
  const date = new Intl.DateTimeFormat('en-IN', { weekday: 'long', month: 'long', day: 'numeric' }).format(new Date())
  const { fullName } = useProfile()
  return <section className="relative isolate overflow-hidden rounded-panel border border-subtle bg-surface shadow-panel">
    <div className="pointer-events-none absolute inset-0 z-0 overflow-hidden" aria-hidden="true"><MotionConfig reducedMotion="never"><motion.div animate={{ rotate: 360 }} transition={{ duration: 30, ease: 'linear', repeat: Infinity }} className="absolute -right-16 -top-20 w-[30rem] opacity-[.48] blur-[.35px] drop-shadow-[0_0_32px_rgb(168_85_247_/_0.2)] sm:-right-12 sm:-top-24 sm:w-[38rem] [will-change:transform]"><DashboardHeroVisual ambient/></motion.div></MotionConfig></div>
    <div className="relative grid min-h-[28rem] gap-8 px-6 py-9 sm:px-8 sm:py-10 lg:grid-cols-[1.08fr_.92fr] lg:px-11 lg:py-10">
      <div className="relative z-10 flex flex-col justify-center"><motion.p initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .4 }} className="eyebrow">{date} · Intelligence workspace</motion.p><motion.h1 initial={{ opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .07, duration: .5 }} className="mt-4 max-w-2xl tracking-display text-4xl font-semibold leading-[1.01] sm:text-5xl xl:text-[3.85rem]">See the reasoning behind the signal.</motion.h1><motion.p initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .15, duration: .5 }} className="mt-5 max-w-xl text-sm leading-7 text-muted sm:text-base">Welcome back, {fullName}. SignalGuard brings your investigation, explainability, and decision-ready intelligence into one dependable workspace.</motion.p><motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .23, duration: .45 }} className="mt-7 flex flex-wrap gap-2.5"><Link to="/app/new-analysis"><Button><Plus size={16}/>New analysis</Button></Link><Link to="/app/text-analysis"><Button variant="secondary"><FileSearch size={15}/>Analyze text</Button></Link><Link to="/app/image-analysis"><Button variant="secondary"><Image size={15}/>Analyze image</Button></Link><Link to="/app/saved-reports"><Button variant="ghost">View reports <ArrowUpRight size={14}/></Button></Link></motion.div>{onContinue && <motion.button initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: .4 }} onClick={onContinue} className="mt-7 inline-flex w-fit items-center gap-2 text-xs font-semibold text-violet hover:text-[#c084fc]">Enter command center <ArrowRight size={14}/></motion.button>}</div>
      <motion.div initial="hidden" animate="visible" variants={{ hidden: {}, visible: { transition: { staggerChildren: .1, delayChildren: .28 } } }} className="relative z-10 col-span-full grid max-w-4xl gap-2 sm:grid-cols-2 lg:grid-cols-3">{status.map((item, index) => <motion.div key={item} variants={{ hidden: { opacity: 0, y: 8 }, visible: { opacity: 1, y: 0 } }} whileHover={{ y: -2 }} className="flex items-center gap-2.5 rounded-control border border-subtle bg-canvas px-3 py-2.5"><span className="relative flex size-2"><span className="absolute inline-flex size-full animate-ping rounded-full bg-success/60"/><span className="relative inline-flex size-2 rounded-full bg-success"/></span><span className="text-xs font-medium">{item}</span>{index === 0 && <Sparkles className="ml-auto text-violet" size={13}/>}</motion.div>)}</motion.div>
      <div className="relative z-10 col-span-full flex flex-wrap items-center gap-x-5 gap-y-2 border-t border-subtle pt-5 text-xs text-muted"><span className="flex items-center gap-1.5"><Activity size={14} className="text-success"/>All systems represented in the interface are ready</span><span>248 analyses this week</span><span>9 reviews awaiting attention</span></div>
    </div>
    <div className="relative overflow-hidden border-t border-subtle bg-canvas py-3"><div className="flex w-max items-center gap-8 whitespace-nowrap [animation:feature-ticker_34s_linear_infinite]">{[...features, ...features].map((feature, index) => <span key={`${feature}-${index}`} className="flex items-center gap-3 font-mono text-[.61rem] uppercase tracking-[.14em] text-muted"><Bot size={13} className="text-violet"/>{feature}</span>)}</div></div>
  </section>
}
