import { motion } from 'framer-motion'
import { BarChart, Donut, Heatmap, TrendChart } from './ChartPrimitives'
import { Panel, SectionTitle } from './PageShell'

export function ExecutiveAnalytics({ risk, confidence, activity }: { risk: number[]; confidence: number[]; activity: number[] }) {
  return <div className="space-y-5"><div className="grid gap-5 xl:grid-cols-2"><Panel><SectionTitle title="Risk trend" description="Confidence-weighted manipulation signal" action={<span className="font-mono text-[.6rem] text-warning">+12.4%</span>}/><TrendChart values={risk} showRangeSwitcher/></Panel><Panel><SectionTitle title="Confidence trend" description="Decision certainty over completed analyses" action={<span className="font-mono text-[.6rem] text-success">+2.1%</span>}/><TrendChart values={confidence}/></Panel></div><div className="grid gap-5 lg:grid-cols-3"><Panel><SectionTitle title="Agent consensus" description="Specialist alignment"/><ConsensusVisual/></Panel><Panel><SectionTitle title="Emotion trend" description="Current emotional signal mix"/><EmotionVisual/></Panel><Panel><SectionTitle title="Detection categories" description="Last 30 days"/><CategoryVisual/></Panel></div><div className="grid gap-5 xl:grid-cols-[.9fr_1.1fr_1.1fr]"><Panel><SectionTitle title="Daily activity" description="Analyses completed"/><BarChart values={activity}/><div className="mt-3 flex justify-between font-mono text-[.58rem] text-muted"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></div></Panel><Panel><SectionTitle title="Signal heatmap" description="Intensity by time window"/><Heatmap/><div className="mt-4 flex justify-between text-[.62rem] text-muted"><span>Lower signal</span><span>Higher signal</span></div></Panel><Panel><SectionTitle title="Executive focus" description="Most influential patterns"/><div className="flex items-center gap-5 py-2"><Donut value={42} label="urgency cues"/><div className="space-y-3 text-xs"><Focus label="Most common" value="Urgency framing"/><Focus label="Psychological principle" value="Scarcity bias"/><Focus label="Peak activity" value="Friday · 16:00"/></div></div></Panel></div></div>
}

export function AdvancedCharts() { return <div className="grid gap-5 lg:grid-cols-2"><Panel><SectionTitle title="Signal distribution" description="Risk and confidence concentration"/><DistributionVisual/></Panel><Panel><SectionTitle title="Evidence scatter" description="Confidence by manipulation intensity"/><ScatterVisual/></Panel><Panel><SectionTitle title="Technique treemap" description="Share of detected techniques"/><TreemapVisual/></Panel><Panel><SectionTitle title="Detection timeline" description="Signal progression across the review window"/><TimelineVisual/></Panel></div> }

function Focus({ label, value }: { label: string; value: string }) { return <div><p className="font-mono text-[.55rem] uppercase tracking-[.1em] text-muted">{label}</p><p className="mt-0.5 text-xs font-semibold text-ink">{value}</p></div> }
function ConsensusVisual() { const agents = [['Intent', 92], ['Context', 89], ['Emotion', 86], ['Strategy', 82]]; return <div className="space-y-4">{agents.map(([agent, value], index) => <div key={agent as string}><div className="mb-1.5 flex justify-between text-xs"><span>{agent as string}</span><span className="font-mono text-muted">{value}%</span></div><div className="h-2 overflow-hidden rounded-full border border-white/[.06] bg-black/20 p-px"><motion.div initial={{ width: 0 }} whileInView={{ width: `${value}%` }} viewport={{ once: true }} transition={{ delay: index * .07, duration: .65 }} className="h-full rounded-full bg-gradient-to-r from-violet/60 to-[#d8b4fe]"/></div></div>)}</div> }
function EmotionVisual() { const values = [['Urgency', 41], ['Fear', 27], ['Trust', 14], ['Neutral', 18]]; return <div className="space-y-3">{values.map(([label, value], index) => <div key={label as string} className="flex items-center gap-3"><span className="w-14 text-[.65rem] text-muted">{label as string}</span><div className="h-2 flex-1 overflow-hidden rounded-full bg-white/[.07]"><motion.div initial={{ width: 0 }} whileInView={{ width: `${value}%` }} viewport={{ once: true }} transition={{ delay: index * .08, duration: .6 }} className="h-full rounded-full bg-gradient-to-r from-violet/60 to-[#d8b4fe]"/></div><span className="w-7 font-mono text-[.62rem] text-violet">{value}%</span></div>)}</div> }
function CategoryVisual() { return <div className="grid grid-cols-2 gap-3"><div className="col-span-2 flex items-center justify-between rounded-xl border border-violet/20 bg-violet/10 p-3"><span className="text-xs font-semibold">Urgency framing</span><span className="font-mono text-lg text-[#d8b4fe]">42%</span></div>{[['Authority bias', '27%'], ['Selective context', '19%'], ['Other', '12%']].map(([label, value]) => <div key={label} className="rounded-lg border border-white/[.07] bg-white/[.025] p-3"><p className="font-mono text-sm text-violet">{value}</p><p className="mt-1 text-[.62rem] text-muted">{label}</p></div>)}</div> }
function DistributionVisual() { const bars = [18, 25, 39, 61, 78, 89, 72, 55, 31, 19]; return <div className="relative flex h-44 items-end gap-2 rounded-xl border border-violet/12 bg-[#17131d]/55 p-4">{bars.map((height, index) => <motion.span key={index} initial={{ height: 0, opacity: 0 }} whileInView={{ height: `${height}%`, opacity: 1 }} viewport={{ once: true }} transition={{ delay: index * .055, duration: .6 }} className="flex-1 rounded-t-[.35rem] bg-gradient-to-t from-violet/35 to-[#d8b4fe]"/>)}</div> }
function ScatterVisual() { const dots = [[12,70],[21,49],[29,62],[39,35],[47,55],[56,24],[65,42],[73,18],[82,31],[91,12]]; return <div className="relative h-44 overflow-hidden rounded-xl border border-violet/12 bg-[#17131d]/55 p-4"><span className="absolute inset-x-4 top-1/2 border-t border-dashed border-white/[.08]"/><span className="absolute bottom-4 left-1/2 top-4 border-l border-dashed border-white/[.08]"/>{dots.map(([x, y], index) => <motion.span key={index} initial={{ scale: 0, opacity: 0 }} whileInView={{ scale: 1, opacity: 1 }} viewport={{ once: true }} transition={{ delay: .12 + index * .06, type: 'spring' }} className="absolute size-2 rounded-full border border-[#e6d7ff] bg-violet shadow-[0_0_12px_rgb(139_92_246_/_0.5)]" style={{ left: `${x}%`, top: `${y}%` }}/>)}</div> }
function TreemapVisual() { return <div className="grid h-44 grid-cols-5 grid-rows-3 gap-2 rounded-xl border border-violet/12 bg-[#17131d]/55 p-3 text-[.62rem] font-semibold"><div className="col-span-3 row-span-2 rounded-lg border border-violet/30 bg-violet/25 p-3">Urgency<br/><span className="font-mono text-violet">42%</span></div><div className="col-span-2 rounded-lg border border-violet/20 bg-violet/15 p-3">Authority<br/><span className="font-mono text-violet">27%</span></div><div className="col-span-2 row-span-2 rounded-lg border border-violet/15 bg-violet/10 p-3">Context<br/><span className="font-mono text-violet">19%</span></div><div className="col-span-3 rounded-lg border border-white/[.08] bg-white/[.035] p-3 text-muted">Other · 12%</div></div> }
function TimelineVisual() { const items = [['08:40', 'Source cluster detected'], ['10:15', 'Urgency signal intensified'], ['12:30', 'Judge consensus reached'], ['14:05', 'Review queue updated']]; return <div className="space-y-3">{items.map(([time, label], index) => <motion.div key={time} initial={{ opacity: 0, x: -8 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }} transition={{ delay: index * .08 }} className="flex items-center gap-3"><span className="font-mono text-[.6rem] text-violet">{time}</span><span className="size-2 rounded-full bg-violet shadow-[0_0_12px_rgb(139_92_246_/_0.65)]"/><span className="text-xs text-muted">{label}</span></motion.div>)}</div> }
