import { Filter, Search, SlidersHorizontal, X } from 'lucide-react'
import { AnimatePresence, motion } from 'framer-motion'
import { useMemo, useState } from 'react'
import { Input } from '../../../components/ui'
import type { IntelligenceReport } from '../data/intelligenceData'

const filters = ['Date', 'Confidence', 'Risk', 'Manipulation type', 'Emotion', 'Source', 'File type', 'Agent', 'Judge decision', 'Meta judge']
export function IntelligenceFilters({ reports, onResults }: { reports: IntelligenceReport[]; onResults: (results: IntelligenceReport[]) => void }) {
  const [open, setOpen] = useState(false)
  const [query, setQuery] = useState('')
  const [riskOnly, setRiskOnly] = useState(false)
  const [fileType, setFileType] = useState<'All' | 'Text' | 'Image'>('All')
  const results = useMemo(() => reports.filter(report => {
    const haystack = `${report.title} ${report.id} ${report.technique} ${report.emotion} ${report.agent} ${report.judge}`.toLowerCase()
    return (!query || haystack.includes(query.toLowerCase())) && (!riskOnly || report.risk >= 60) && (fileType === 'All' || report.fileType === fileType)
  }), [fileType, query, reports, riskOnly])
  const apply = (nextQuery = query, nextRisk = riskOnly, nextType = fileType) => { const next = reports.filter(report => { const haystack = `${report.title} ${report.id} ${report.technique} ${report.emotion} ${report.agent} ${report.judge}`.toLowerCase(); return (!nextQuery || haystack.includes(nextQuery.toLowerCase())) && (!nextRisk || report.risk >= 60) && (nextType === 'All' || report.fileType === nextType) }); onResults(next) }
  return <div className="rounded-panel border border-violet/15 bg-[#17131d]/70 p-3 shadow-[inset_0_1px_0_rgb(255_255_255_/_0.04)]"><div className="flex flex-col gap-3 lg:flex-row lg:items-center"><div className="relative min-w-0 flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-muted" size={16}/><Input value={query} onChange={event => { setQuery(event.target.value); apply(event.target.value) }} className="h-10 pl-10" placeholder="Search reports, evidence, techniques, emotions, agents, or decisions"/></div><div className="flex flex-wrap gap-2"><button onClick={() => setOpen(value => !value)} className="inline-flex h-10 items-center gap-2 rounded-control border border-subtle bg-canvas/60 px-3 text-xs font-semibold text-muted transition hover:border-violet/35 hover:text-ink"><SlidersHorizontal size={14}/>Advanced filters</button><button onClick={() => { setRiskOnly(false); setFileType('All'); setQuery(''); onResults(reports) }} className="inline-flex h-10 items-center gap-2 rounded-control border border-subtle px-3 text-xs text-muted transition hover:text-ink"><X size={14}/>Clear</button></div></div><AnimatePresence>{open && <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }} className="overflow-hidden"><div className="mt-3 flex flex-wrap gap-2 border-t border-white/[.07] pt-3"><span className="inline-flex items-center gap-1.5 px-1 text-[.62rem] font-mono uppercase tracking-[.1em] text-violet"><Filter size={12}/>Filters</span>{filters.map(filter => <button key={filter} onClick={() => filter === 'Risk' && (() => { const next = !riskOnly; setRiskOnly(next); apply(query, next) })()} className={`rounded-full border px-3 py-1.5 text-[.65rem] font-medium transition ${filter === 'Risk' && riskOnly ? 'border-violet/40 bg-violet/15 text-violet' : 'border-white/[.09] bg-white/[.025] text-muted hover:text-ink'}`}>{filter}{filter === 'Risk' && riskOnly ? ' ≥ 60' : ''}</button>)}{(['All', 'Text', 'Image'] as const).map(type => <button key={type} onClick={() => { setFileType(type); apply(query, riskOnly, type) }} className={`rounded-full border px-3 py-1.5 text-[.65rem] transition ${fileType === type ? 'border-violet/40 bg-violet/15 text-violet' : 'border-white/[.09] text-muted'}`}>{type}</button>)}</div></motion.div>}</AnimatePresence><p className="mt-3 px-1 font-mono text-[.57rem] uppercase tracking-[.11em] text-muted">{results.length} matching intelligence records</p></div>
}
