import { Download, FileJson, FileSpreadsheet, FileText, MonitorUp, Presentation, ShieldCheck } from 'lucide-react'
import { motion } from 'framer-motion'
import { useState } from 'react'
import { Button, Dropdown } from '../../../components/ui'
import { AdvancedCharts, ExecutiveAnalytics } from '../components/IntelligenceVisuals'
import { IntelligenceFilters } from '../components/IntelligenceFilters'
import { InsightCard } from '../components/InsightCard'
import { MetricCard, PageShell, Panel, SectionTitle } from '../components/PageShell'
import { executiveSeries, intelligenceInsights, intelligenceMetrics, intelligenceReports, type IntelligenceReport } from '../data/intelligenceData'

export function IntelligenceCenterPage() {
  const [executiveMode, setExecutiveMode] = useState(false)
  const [results, setResults] = useState<IntelligenceReport[]>(intelligenceReports)
  return <PageShell eyebrow="AI intelligence platform" title="Intelligence Center" description="Long-term manipulation intelligence, decision trends, and research-ready workspace signals." action={<div className="flex flex-wrap gap-2"><Dropdown trigger={<Button variant="secondary"><Download size={15}/>Export</Button>}><div className="space-y-1 p-1">{[[FileText, 'PDF report'], [FileSpreadsheet, 'CSV dataset'], [FileJson, 'JSON intelligence'], [MonitorUp, 'PNG snapshot']].map(([Icon, label]) => { const ExportIcon = Icon as typeof FileText; return <button key={label as string} className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-left text-xs text-muted transition hover:bg-white/[.05] hover:text-ink"><ExportIcon size={14}/>{label as string}<span className="ml-auto font-mono text-[.55rem] uppercase text-violet">Ready</span></button> })}</div></Dropdown><Button variant={executiveMode ? 'primary' : 'secondary'} onClick={() => setExecutiveMode(value => !value)}><Presentation size={15}/>{executiveMode ? 'Exit executive' : 'Executive mode'}</Button></div>}>
    <div className={executiveMode ? 'mx-auto max-w-6xl' : ''}>
      <div className="mb-5 flex items-center gap-2 rounded-control border border-violet/20 bg-violet/[.07] px-4 py-3 text-xs text-muted"><ShieldCheck size={15} className="text-violet"/><span><b className="font-semibold text-ink">Intelligence status:</b> Frontend preview data is active. Live aggregate data will plug into these same view models when available.</span></div>
      {!executiveMode && <IntelligenceFilters reports={intelligenceReports} onResults={setResults}/>} 
      <section className="mt-5"><div className="mb-4 flex items-end justify-between gap-4"><div><p className="eyebrow">Workspace health</p><h2 className="mt-1 text-lg font-semibold">Decision intelligence at a glance</h2></div><span className="font-mono text-[.6rem] uppercase tracking-[.12em] text-success">Systems nominal</span></div><div className={`grid gap-4 ${executiveMode ? 'sm:grid-cols-3' : 'sm:grid-cols-2 xl:grid-cols-3'}`}>{intelligenceMetrics.map((metric, index) => <motion.div key={metric.label} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .045 }}><MetricCard label={metric.label} value={metric.value} detail={`${metric.detail} · ${metric.trend}`} tone={metric.tone}/></motion.div>)}</div></section>
      <section className="mt-6"><div className="mb-4"><p className="eyebrow">Executive analytics</p><h2 className="mt-1 text-lg font-semibold">Patterns that need attention</h2></div><ExecutiveAnalytics {...executiveSeries}/></section>
      {!executiveMode && <><section className="mt-6"><div className="mb-4"><p className="eyebrow">AI insights</p><h2 className="mt-1 text-lg font-semibold">Emerging manipulation patterns</h2></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{intelligenceInsights.map((insight, index) => <InsightCard key={insight.title} insight={insight} index={index}/>)}</div></section><section className="mt-6"><div className="mb-4"><p className="eyebrow">Advanced visual analysis</p><h2 className="mt-1 text-lg font-semibold">Distribution, evidence, and timeline views</h2></div><AdvancedCharts/></section><section className="mt-6"><Panel><SectionTitle title="Filtered intelligence records" description="Client-side preview of the unified report, evidence, agent, and decision search index"/><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead className="border-b border-white/[.08] font-mono text-[.58rem] uppercase tracking-[.1em] text-muted"><tr><th className="pb-3 font-medium">Report</th><th className="pb-3 font-medium">Risk</th><th className="pb-3 font-medium">Confidence</th><th className="pb-3 font-medium">Technique</th><th className="pb-3 font-medium">Emotion</th><th className="pb-3 font-medium">Decision</th></tr></thead><tbody>{results.map(report => <tr key={report.id} className="border-b border-white/[.06] last:border-0"><td className="py-3"><p className="font-semibold text-ink">{report.title}</p><p className="mt-0.5 font-mono text-[.58rem] text-muted">{report.id} · {report.source}</p></td><td className="py-3 font-mono text-violet">{report.risk}/100</td><td className="py-3 font-mono text-muted">{report.confidence}%</td><td className="py-3 text-muted">{report.technique}</td><td className="py-3 text-muted">{report.emotion}</td><td className="py-3"><span className={`rounded-full px-2 py-1 text-[.6rem] font-semibold ${report.judge === 'Review' ? 'bg-warning/10 text-warning' : 'bg-success/10 text-success'}`}>{report.judge} · {report.metaJudge}</span></td></tr>)}</tbody></table></div></Panel></section></>}
    </div>
  </PageShell>
}
